### ISSUE TITLE
try to remove MsExperiment, only require Spectra

### ISSUE THREAD

**Issue by tnaake** [tnaake/MsQuality#8]
Use information stored in `Spectra` object to split samples and calculate metrics from `Spectra` data only.

**Comment by jorainer** [comment]
You could/should use the `dataOrigin` spectra variable for that. That one should store the information from which original (raw) file the data was imported. Ideally, I would suggest to have this as a paramter to the function to give the user also the freedom to chose an alternative variable that defines samples:

To calculate the metrics for spectra grouped by parameter `f` (could also be another name for the parameter):

```r
function(object, f = object$dataOrigin, ...)
```
